### ISSUE TITLE
[Feature Request] Limit Failure Messages

### ISSUE THREAD

**Issue by Xdomen** [jackcoded/newman-reporter-slackmsg#20]
First of all, thanks for providing such a great feature! It is really useful. 

I have an issue when testing a large collection of tests where they occasionally fail due to network issues / misconfigured servers. This causes a lot of assertion failures, which completely spams slack with the failure messages.

```
Endpoint 1
1. AssertionError - Status code return 200
• Expected - response to have status code 200 but got 404
2. AssertionError - Status response is JSON
• Expected - response body to be a valid json but got error Unexpected token < at 1:1
3. JSONError - connection error
• UnExpected - token < at 1:1<!DOCTYPE html>^
``` 

 
Could you please implement an optional parameter that would limit failure message lines to any desired number. i.e display only 10 assertion failures.

` --reporter-slackmsg-limitFailures '<50>' ` 

This would help us a lot! 

Thanks.

**Comment by jackcoded** [comment]
Added feature been busy with life
