### ISSUE TITLE
Show name of collection and environmenst

### ISSUE THREAD

**Issue by bergstedtniclas** [jackcoded/newman-reporter-slackmsg#3]
Hi there!
I really like this slack-reporter to newman.
So much better than the others.

But there is one thing I'm missing.
And the thing that I'm missing is that you cant see what collection or environment file that's been used.

It would be really nice if you could add this feature.
Maybe place this in top of everything.
Like...

--------------------

Collection:
Environment:

**Test Summary**

Totalt Tests
etc
etc

-------------------

And maybe also add number of assertions to the test summary?

Best regards Niclas

**Comment by jackcoded** [comment]
Hey bergstedtniclas,

Thanks for the support i'll implement your suggestion right now.

Cheers,
Jack

**Comment by bergstedtniclas** [comment]
Cool! :) Thank you!

Cheers,
Niclas

**Comment by jackcoded** [comment]
Hey Niclas, 
Sorry for the delay, i've updated the reporter now to include ur changes and more. Please test it out if it's working for you.

Cheers,
Jack
